### ISSUE TITLE
US 11.17, click "GO GO!", crashes with "An error has occurred. Please save your data in any software currently in use, and then restart the system."

### ISSUE THREAD

**Issue by Wiresgaming** [zoogie/super-skaterhax#11]

**Comment by zoogie** [comment]
last bullet point here:
https://github.com/zoogie/super-skaterhax#troubleshooting-hbmenu

**Comment by thartzheim** [comment]
@Wiresgaming make sure the date is set correctly on your device. I was having this same issue, then fixed the date and now it worked first try.

**Comment by Wiresgaming** [comment]
Device time was incorrect, off by a year. Thanks!
