### ISSUE TITLE
GO! GO! not loading or downloading anything

### ISSUE THREAD

**Issue by grmdrk** [zoogie/super-skaterhax#13]
When I click the link in the 3ds browser it just take me to a blank screen, sometimes with an empty box with the word "text" in the top left. Have I messed up somewhere with the files to put on the memory card or is this a known issue? I've tried deleting cookies and history, restarting the console, double checking the files I have on the SD, everything looks right but this is always the dead for me.

**Comment by zoogie** [comment]
New 3DS only.
