### ISSUE TITLE
browserhax_hblauncher_ropbin_payload.bin

### ISSUE THREAD

**Issue by TheDinoSide** [zoogie/super-skaterhax#16]
browserhax_hblauncher_ropbin_payload.bin is unable to be found so i don't know if you changed the name or removed it

**Comment by zoogie** [comment]
Just checked; it's still in the release archive.

**Comment by TheDinoSide** [comment]
How to do i access the release archive because i can't find it.

**Comment by zoogie** [comment]
https://github.com/zoogie/super-skaterhax/releases/download/v1.1/release_new3ds_v1.1.zip

**Comment by TheDinoSide** [comment]
thank you for the help.
